export const ROUTE_PATHS = {
    AUTH: 'auth',
    HOME: 'home',
    CLIENTS: 'clients',
    CLIENT_DETAILS: 'clients/:clientId',
    USERS: 'users',
    USER_DETAILS: 'users/:userId',
    DEBTORS_LIST: 'users/:userId/debtors-list',
    REPORTS: 'reports',
    SUPPORT: 'support',
    SUPPORT_CONTACT: 'support/contact',
    ACCOUNT: 'account',
    USER_ID: ':userId',
    ACCOUNT_PROFILE: 'profile',
    ACCOUNT_SETTINGS: 'settings',
    FORBIDDEN: 'forbidden',
    NOT_FOUND: '**',
    REDIRECT: '',
};


export const ROUTE_TITLES = {
    HOME: 'FinApp | Home',
    CLIENTS: 'FinApp | Clients',
    USERS: 'FinApp | Users',
    USER: 'FinApp | User',
    DEBTORS_LIST: 'FinApp | Debtors List',
    REPORTS: 'FinApp | Reports',
    SUPPORT: 'FinApp | Support',
    ACCOUNT: 'Account Settings',
    PROFILE: 'Profile',
    SETTINGS: 'Settings',
    FORBIDDEN: '403 | Forbidden',
    NOT_FOUND: '404 | Not Found',
};